#!/bin/bash

while true; do

	dwmupdates > /home/steve/dwmscripts/dwmupdates.txt

	sleep 3600s

done &

while true; do

	CPU=$(dwmcpu)
	MEM=$(dwmmemory)
	NET=$(dwmnet)
	TEMP=$(dwmtemp)
	HDD=$(dwmdisk)
	UPDATES=$(< /home/steve/dwmscripts/dwmupdates.txt)
	BATT=$(dwmbatt)
	TIME=$(dwmclock)
	xsetroot -name "| $CPU | $MEM | $NET | $TEMP | $HDD | $UPDATES | $BATT | $TIME"

	sleep 5s
	
done &
